// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/contact" | "/courses" | "/courses/[id]" | "/faculty" | "/faculty/attendance" | "/faculty/communications" | "/faculty/lectures" | "/faculty/materials" | "/faculty/settings" | "/faculty/students" | "/faculty/timetable" | "/learn/[id]" | "/login" | "/playground" | "/student" | "/student/announcements" | "/student/assignments" | "/student/attendance" | "/student/courses" | "/student/materials" | "/student/settings" | "/student/timetable" | "/sub-admin" | "/sub-admin/analytics" | "/sub-admin/attendance" | "/sub-admin/audit" | "/sub-admin/communications" | "/sub-admin/configuration" | "/sub-admin/courses" | "/sub-admin/faculty" | "/sub-admin/lectures" | "/sub-admin/settings" | "/sub-admin/students" | "/super-admin" | "/super-admin/attendance" | "/super-admin/branches" | "/super-admin/communications" | "/super-admin/courses" | "/super-admin/reports" | "/super-admin/settings" | "/super-admin/team"
type AppRouteHandlerRoutes = "/api/admin/create-student" | "/api/admins" | "/api/attendance" | "/api/auth" | "/api/branches" | "/api/branches/[id]" | "/api/courses" | "/api/execute" | "/api/faculties" | "/api/lecture-plans" | "/api/mentor" | "/api/notices" | "/api/razorpay/order" | "/api/razorpay/verify" | "/api/staff-attendance" | "/api/student-daily-attendance" | "/api/students" | "/api/test-db"
type PageRoutes = never
type LayoutRoutes = "/" | "/faculty" | "/student" | "/sub-admin" | "/super-admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/admin/create-student": {}
  "/api/admins": {}
  "/api/attendance": {}
  "/api/auth": {}
  "/api/branches": {}
  "/api/branches/[id]": { "id": string; }
  "/api/courses": {}
  "/api/execute": {}
  "/api/faculties": {}
  "/api/lecture-plans": {}
  "/api/mentor": {}
  "/api/notices": {}
  "/api/razorpay/order": {}
  "/api/razorpay/verify": {}
  "/api/staff-attendance": {}
  "/api/student-daily-attendance": {}
  "/api/students": {}
  "/api/test-db": {}
  "/contact": {}
  "/courses": {}
  "/courses/[id]": { "id": string; }
  "/faculty": {}
  "/faculty/attendance": {}
  "/faculty/communications": {}
  "/faculty/lectures": {}
  "/faculty/materials": {}
  "/faculty/settings": {}
  "/faculty/students": {}
  "/faculty/timetable": {}
  "/learn/[id]": { "id": string; }
  "/login": {}
  "/playground": {}
  "/student": {}
  "/student/announcements": {}
  "/student/assignments": {}
  "/student/attendance": {}
  "/student/courses": {}
  "/student/materials": {}
  "/student/settings": {}
  "/student/timetable": {}
  "/sub-admin": {}
  "/sub-admin/analytics": {}
  "/sub-admin/attendance": {}
  "/sub-admin/audit": {}
  "/sub-admin/communications": {}
  "/sub-admin/configuration": {}
  "/sub-admin/courses": {}
  "/sub-admin/faculty": {}
  "/sub-admin/lectures": {}
  "/sub-admin/settings": {}
  "/sub-admin/students": {}
  "/super-admin": {}
  "/super-admin/attendance": {}
  "/super-admin/branches": {}
  "/super-admin/communications": {}
  "/super-admin/courses": {}
  "/super-admin/reports": {}
  "/super-admin/settings": {}
  "/super-admin/team": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/faculty": never
  "/student": never
  "/sub-admin": never
  "/super-admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
