// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/courses/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/courses/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/courses/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/courses">> = Specific
  const handler = {} as typeof import("../../../src/app/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/faculty/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faculty/attendance">> = Specific
  const handler = {} as typeof import("../../../src/app/faculty/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/faculty/communications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faculty/communications">> = Specific
  const handler = {} as typeof import("../../../src/app/faculty/communications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/faculty/lectures/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faculty/lectures">> = Specific
  const handler = {} as typeof import("../../../src/app/faculty/lectures/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/faculty/materials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faculty/materials">> = Specific
  const handler = {} as typeof import("../../../src/app/faculty/materials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/faculty/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faculty">> = Specific
  const handler = {} as typeof import("../../../src/app/faculty/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/faculty/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faculty/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/faculty/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/faculty/students/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faculty/students">> = Specific
  const handler = {} as typeof import("../../../src/app/faculty/students/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/faculty/timetable/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faculty/timetable">> = Specific
  const handler = {} as typeof import("../../../src/app/faculty/timetable/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/learn/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learn/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/learn/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/playground/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/playground">> = Specific
  const handler = {} as typeof import("../../../src/app/playground/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/student/announcements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/announcements">> = Specific
  const handler = {} as typeof import("../../../src/app/student/announcements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/student/assignments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/assignments">> = Specific
  const handler = {} as typeof import("../../../src/app/student/assignments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/student/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/attendance">> = Specific
  const handler = {} as typeof import("../../../src/app/student/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/student/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/courses">> = Specific
  const handler = {} as typeof import("../../../src/app/student/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/student/materials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/materials">> = Specific
  const handler = {} as typeof import("../../../src/app/student/materials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/student/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student">> = Specific
  const handler = {} as typeof import("../../../src/app/student/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/student/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/student/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/student/timetable/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/timetable">> = Specific
  const handler = {} as typeof import("../../../src/app/student/timetable/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sub-admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sub-admin/analytics">> = Specific
  const handler = {} as typeof import("../../../src/app/sub-admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sub-admin/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sub-admin/attendance">> = Specific
  const handler = {} as typeof import("../../../src/app/sub-admin/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sub-admin/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sub-admin/audit">> = Specific
  const handler = {} as typeof import("../../../src/app/sub-admin/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sub-admin/communications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sub-admin/communications">> = Specific
  const handler = {} as typeof import("../../../src/app/sub-admin/communications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sub-admin/configuration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sub-admin/configuration">> = Specific
  const handler = {} as typeof import("../../../src/app/sub-admin/configuration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sub-admin/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sub-admin/courses">> = Specific
  const handler = {} as typeof import("../../../src/app/sub-admin/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sub-admin/faculty/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sub-admin/faculty">> = Specific
  const handler = {} as typeof import("../../../src/app/sub-admin/faculty/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sub-admin/lectures/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sub-admin/lectures">> = Specific
  const handler = {} as typeof import("../../../src/app/sub-admin/lectures/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sub-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sub-admin">> = Specific
  const handler = {} as typeof import("../../../src/app/sub-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sub-admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sub-admin/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/sub-admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sub-admin/students/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sub-admin/students">> = Specific
  const handler = {} as typeof import("../../../src/app/sub-admin/students/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/super-admin/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/attendance">> = Specific
  const handler = {} as typeof import("../../../src/app/super-admin/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/super-admin/branches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/branches">> = Specific
  const handler = {} as typeof import("../../../src/app/super-admin/branches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/super-admin/communications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/communications">> = Specific
  const handler = {} as typeof import("../../../src/app/super-admin/communications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/super-admin/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/courses">> = Specific
  const handler = {} as typeof import("../../../src/app/super-admin/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/super-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin">> = Specific
  const handler = {} as typeof import("../../../src/app/super-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/super-admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/reports">> = Specific
  const handler = {} as typeof import("../../../src/app/super-admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/super-admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/super-admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/super-admin/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/team">> = Specific
  const handler = {} as typeof import("../../../src/app/super-admin/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/create-student/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/create-student">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/create-student/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admins/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admins">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admins/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/attendance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance">> = Specific
  const handler = {} as typeof import("../../../src/app/api/attendance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/branches/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/branches/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/branches/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/branches/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/branches">> = Specific
  const handler = {} as typeof import("../../../src/app/api/branches/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/courses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/courses">> = Specific
  const handler = {} as typeof import("../../../src/app/api/courses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/execute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/execute">> = Specific
  const handler = {} as typeof import("../../../src/app/api/execute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/faculties/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/faculties">> = Specific
  const handler = {} as typeof import("../../../src/app/api/faculties/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/lecture-plans/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lecture-plans">> = Specific
  const handler = {} as typeof import("../../../src/app/api/lecture-plans/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/mentor/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mentor">> = Specific
  const handler = {} as typeof import("../../../src/app/api/mentor/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/notices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notices">> = Specific
  const handler = {} as typeof import("../../../src/app/api/notices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/razorpay/order/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/razorpay/order">> = Specific
  const handler = {} as typeof import("../../../src/app/api/razorpay/order/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/razorpay/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/razorpay/verify">> = Specific
  const handler = {} as typeof import("../../../src/app/api/razorpay/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/staff-attendance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff-attendance">> = Specific
  const handler = {} as typeof import("../../../src/app/api/staff-attendance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/student-daily-attendance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/student-daily-attendance">> = Specific
  const handler = {} as typeof import("../../../src/app/api/student-daily-attendance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/students/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/students">> = Specific
  const handler = {} as typeof import("../../../src/app/api/students/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/faculty/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/faculty">> = Specific
  const handler = {} as typeof import("../../../src/app/faculty/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/student/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/student">> = Specific
  const handler = {} as typeof import("../../../src/app/student/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sub-admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/sub-admin">> = Specific
  const handler = {} as typeof import("../../../src/app/sub-admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/super-admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/super-admin">> = Specific
  const handler = {} as typeof import("../../../src/app/super-admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
