var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/sub-admin/analytics/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__e51dd5a7._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_8a097556._.js")
R.c("server/chunks/ssr/[root-of-the-server]__adde7365._.js")
R.c("server/chunks/ssr/node_modules_63dba3f8._.js")
R.c("server/chunks/ssr/node_modules_7cb79fa0._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/src_d60c0231._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_sub-admin_layout_tsx_22dcb806._.js")
R.c("server/chunks/ssr/_next-internal_server_app_sub-admin_analytics_page_actions_858c902a.js")
R.m(40212)
module.exports=R.m(40212).exports
