var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/sub-admin/configuration/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__96978ef7._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_261d458e._.js")
R.c("server/chunks/ssr/[root-of-the-server]__adde7365._.js")
R.c("server/chunks/ssr/node_modules_63dba3f8._.js")
R.c("server/chunks/ssr/node_modules_7cb79fa0._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/src_d60c0231._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_sub-admin_layout_tsx_22dcb806._.js")
R.c("server/chunks/ssr/_next-internal_server_app_sub-admin_configuration_page_actions_605e839f.js")
R.m(22285)
module.exports=R.m(22285).exports
