var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/super-admin/team/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__e4deab3a._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_ffaf819d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__adde7365._.js")
R.c("server/chunks/ssr/node_modules_63dba3f8._.js")
R.c("server/chunks/ssr/node_modules_7cb79fa0._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/src_d60c0231._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_super-admin_layout_tsx_5d4a3a00._.js")
R.c("server/chunks/ssr/_next-internal_server_app_super-admin_team_page_actions_7a195faf.js")
R.m(33215)
module.exports=R.m(33215).exports
